<?xml version="1.0"?>
<package format="3">
  <name>eyou_ethercat_bringup</name>
  <version>0.0.1</version>
  <description>EYOU EtherCAT bringup</description>
  <maintainer email="you@example.com">you</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>controller_manager</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend>
  <exec_depend>joint_trajectory_controller</exec_depend>
  <exec_depend>forward_command_controller</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>robot_model</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>ethercat_driver</exec_depend>
  <exec_depend>ethercat_generic_cia402_drive</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>